### ISSUE TITLE
NewrelicNavigationObserver throws error when go_router uses NoTransitionPage

### ISSUE THREAD

**Issue by codercr** [newrelic/newrelic-flutter-agent#35]
When using a router with a go_router NoTransitionPage base, NewrelicNavigationObserver throws an error because it only expects a previous route to be of type MaterialPage if new route is of type MaterialPage. This is an incorrect assumption as go_router uses CustomTransitionPage base class which is not related to MaterialPage.

https://github.com/newrelic/newrelic-flutter-agent/blame/017416eb6bede3de86319807ab52568a91223063/lib/newrelic_navigation_observer.dart#L19

**Comment by ndesai-newrelic** [comment]
@codercr Thank you for drawing attention to this issue. I will investigate it further on my end, and we plan to address it in the upcoming release.

**Comment by ndesai-newrelic** [comment]
@codercr issue is fixed in latest flutter agent release.

**Comment by codercr** [comment]
@ndesai-newrelic my apologies. We are using go_router_flow and not go_router. The issue happens with the latest release.

**Comment by ndesai-newrelic** [comment]
@codercr can you share package link? I am unable to find it on pub.dev.

**Comment by codercr** [comment]
I will close this issue. Looks like the library was discontinued. My apologies.

**Comment by codercr** [comment]
@ndesai-newrelic - I switched to the latest go_router and still get the error.

`go_router: ^10.0.0`

I have a material page that pushes a route that uses a `NoTransitionPage` to void transition animation on tab selection.

**Comment by ndesai-newrelic** [comment]
@codercr what error are you getting?

**Comment by codercr** [comment]
This is the error we are getting.

<img width="379" alt="Screen Shot 2023-08-06 at 7 41 30 PM" src="https://github.com/newrelic/newrelic-flutter-agent/assets/1117097/f9689f34-b65a-4c20-a474-675a809ee98f">

**Comment by ndesai-newrelic** [comment]
@codercr can you share code snippet for this error?

**Comment by codercr** [comment]
The NewRelic code assume that a `MaterialPage` can only have a child of type `MaterialPage`. This is not so, as transitions can occur on any route using `CustomTransitionPage` which `NoTransitionPage` extends from.

https://github.com/newrelic/newrelic-flutter-agent/blame/017416eb6bede3de86319807ab52568a91223063/lib/newrelic_navigation_observer.dart#L19

**Comment by ndesai-newrelic** [comment]
@codercr can you try our latest release 1.0.3 ?

**Comment by codercr** [comment]
I am attempting to use release 1.0.3 and getting this error.

```
    [!] CocoaPods could not find compatible versions for pod "NewRelicAgent":
      In snapshot (Podfile.lock):
        NewRelicAgent (= 7.4.5)

      In Podfile:
        newrelic_mobile (from `.symlinks/plugins/newrelic_mobile/ios`) was resolved to 1.0.3, which depends on
          NewRelicAgent (= 7.4.6)
```

**Comment by ndesai-newrelic** [comment]
@codercr you just need to delete your Podfile.lock and run pod install again.

**Comment by codercr** [comment]
resolved with latest release.
